### ISSUE TITLE
Session 1: Web Mechanics Speed Dating

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/offline-icebreakers#1]
- [x] Localizar
- [x] Revisar
- [x] Submeter

**Comment by barrosgg** [comment]
Eu vou trabalhar na localização desta atividade hoje. 👍

**Comment by barrosgg** [comment]
@mchagas já está revisado?

**Comment by maykonchagas** [comment]
@barrosgeraldo pronto, revisado e pronto pra submissão! XD

**Comment by barrosgg** [comment]
Vou submeter esse.

**Comment by barrosgg** [comment]
@mchagas, obrigado pelo apoio. <3
