### ISSUE TITLE
Session 2: HTML Thimble Tag Puzzle

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/offline-icebreakers#2]
- [x] Localizar
- [x] Revisar
- [x] Submeter

**Comment by barrosgg** [comment]
Localize esta atividade diretamente do seu navegador:
https://github.com/mozillabrasil/offline-icebreakers/blob/gh-pages/session02-html-thimble-tag-puzzle.html

**Comment by igorgoncalves** [comment]
Tem um problema com um link que vai pro www.makes.org, tem um projeto do thimble lá. 

https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners

**Comment by ThiagoEscarrone** [comment]
Essa issue é minha. :D

**Comment by maykonchagas** [comment]
@jaimemaretoli quando puder, dá um oi por aqui e diz como está o status da revisão!

**Comment by barrosgg** [comment]
@jaimemaretoli, revisado aqui?

**Comment by jaimemaretoli** [comment]
@barrosgeraldo @mchagas @ThiagoEscarrone Revisão finalizada. Podem submeter!

**Comment by barrosgg** [comment]
@ThiagoEscarrone, submeta esta atividade, pls. :)
