### ISSUE TITLE
Session 3: Puzzles for Teaching HTML

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/offline-icebreakers#3]
- [x] Localizar
- [x] Revisar
- [x] Submeter

**Comment by barrosgg** [comment]
https://github.com/mozillabrasil/offline-icebreakers/blob/gh-pages/session03-puzzles-for-teaching-html.html

**Comment by barrosgg** [comment]
@mchagas eu revisei este agora, enviei um commit e já está pronto para você submeter.

**Comment by maykonchagas** [comment]
@barrosgeraldo obrigado você!
