### ISSUE TITLE
Session 4: A Strong Wind

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/offline-icebreakers#4]
- [ ] Localizar
- [ ] Revisar
- [ ] Submeter

**Comment by barrosgg** [comment]
https://github.com/mozillabrasil/offline-icebreakers/blob/gh-pages/session04-a-strong-wind.html

**Comment by maribeiromendes** [comment]
@barrosgeraldo xD

**Comment by barrosgg** [comment]
Mariana, aceite o convite para atribuir esta a você.

**Comment by barrosgg** [comment]
Atualizações aqui?

**Comment by barrosgg** [comment]
Acho que foi localizada e precisa de revisão, correto @meldenne ?

**Comment by maykonchagas** [comment]
@barrosgeraldo o @FabioBeneditto se disponibilizou para realizar a revisão.

**Comment by FabioBeneditto** [comment]
Calma, vai dar certo 😸

**Comment by maykonchagas** [comment]
Não vai dar. Já deu! Maravilhaa!!
