### ISSUE TITLE
Session 5: Web Literacy Bingo

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/offline-icebreakers#5]
- [x] Localizar
- [x] Revisar
- [x] Submeter

**Comment by barrosgg** [comment]
https://github.com/mozillabrasil/offline-icebreakers/blob/gh-pages/session05-web-literacy-bingo.html

**Comment by FabioBeneditto** [comment]
Quem faz a submissão? @barrosgeraldo ou @mchagas ?

**Comment by barrosgg** [comment]
@FabioBeneditto quem localizou faz a submissão e também adiciona o nome de todos que colaboraram.

**Comment by maykonchagas** [comment]
@cynthiapereira por favor, assim que puder, siga as instruções de submissão descritas aqui no README ou através do email que eu passei alguns dias atrás.

Lembre de informar o nome e email de todos os envolvidos, conforme sugestão do email.

**Comment by cpswsg** [comment]
@mchagas Atividade submetida!
