### ISSUE TITLE
Session 6: HTML Puzzle Box

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/offline-icebreakers#6]
- [x] Localizar
- [x] Revisar
- [x] Submeter

**Comment by barrosgg** [comment]
https://github.com/mozillabrasil/offline-icebreakers/blob/gh-pages/session06-html-puzzle-box.html

**Comment by maykonchagas** [comment]
@IgorGoncalves por favor, assim que puder, siga as instruções de submissão descritas aqui no README ou através do email que eu passei alguns dias atrás.

Lembre de informar o nome e email de todos os envolvidos, conforme sugestão do email.

**Comment by igorgoncalves** [comment]
Enviado :D
